### ISSUE TITLE
Crash if internet connection isn't available

### ISSUE THREAD

**Issue by FRizzonelli** [chinoio/chino-nodejs#1]
Hello,

great job on the Sdk and the documentation!

Just a small issue, if you run your node server and you have no connectivity, SDK will crash inside _apiCall.js_

```
/** Manage response from Chino API
 *
 * @param error
 * @param response
 */
function responseHandler(error, response) {
  if (error) {
    this.reject(response.body || error);
  }
  else {
    this.resolve(response.body);
  }
}
```

Response will be **undefined**, could you just add another check on this?

Thank you!

**Comment by aarighi** [comment]
This repository has been migrated to https://gitlab.com/chinoio-public/sdk-chino-nodejs and will no longer be maintained on GitHub. Please reach out to [tech-support@chino.io](mailto:tech-support@chino.io) for any question, or if you wish to contribute to the SDK development.
