### ISSUE TITLE
Blob Upload sequence instead of parallel

### ISSUE THREAD

**Issue by esseti** [chinoio/chino-nodejs#2]
The blob chunk uploads is executed in parallel, this means a lot of calls to the server which may block or stop the calls if they are too many.

The solution is to make it sequential or to do buckets of 10 parallel calls at maximum.

**Comment by aarighi** [comment]
This repository has been migrated to https://gitlab.com/chinoio-public/sdk-chino-nodejs and will no longer be maintained on GitHub. Please reach out to [tech-support@chino.io](mailto:tech-support@chino.io) for any question, or if you wish to contribute to the SDK development.
