### ISSUE TITLE
Revoke token isn't working properly

### ISSUE THREAD

**Issue by FRizzonelli** [chinoio/chino-nodejs#3]
I think there is some problem on server side, after calling **/auth/revoke_token** via node.js client or via API directly, the token is still valid.
I'm generating a _new Chino(baseUrl, token)_ every request I receive, so I'd expect to receive a 401 after calling **/auth/revoke_token**.
The response is correct (I'm receiving 200 OK) but the token needs to be invalidated

**Comment by fedriz** [comment]
+1

**Comment by aarighi** [comment]
This repository has been migrated to https://gitlab.com/chinoio-public/sdk-chino-nodejs and will no longer be maintained on GitHub. Please reach out to [tech-support@chino.io](mailto:tech-support@chino.io) for any question, or if you wish to contribute to the SDK development.
